# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Personal_Project/8B-10B-Encoder-Decoder/Dec8B10B/Dec8B10B.cache/wt [current_project]
set_property parent.project_path D:/Personal_Project/8B-10B-Encoder-Decoder/Dec8B10B/Dec8B10B.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Personal_Project/8B-10B-Encoder-Decoder/Dec8B10B/Dec8B10B.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Personal_Project/8B-10B-Encoder-Decoder/Dec8B10B/Dec8B10B.srcs/sources_1/new/disCtrl.v
  D:/Personal_Project/8B-10B-Encoder-Decoder/Dec8B10B/Dec8B10B.srcs/sources_1/new/fcn4b3b.v
  D:/Personal_Project/8B-10B-Encoder-Decoder/Dec8B10B/Dec8B10B.srcs/sources_1/new/fcn6b.v
  D:/Personal_Project/8B-10B-Encoder-Decoder/Dec8B10B/Dec8B10B.srcs/sources_1/new/fcn6b5b.v
  D:/Personal_Project/8B-10B-Encoder-Decoder/Dec8B10B/Dec8B10B.srcs/sources_1/new/inCheck.v
  D:/Personal_Project/8B-10B-Encoder-Decoder/Dec8B10B/Dec8B10B.srcs/sources_1/new/Dec8B10B.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Personal_Project/8B-10B-Encoder-Decoder/Dec8B10B/Dec8B10B.srcs/constrs_1/new/Constraint1.xdc
set_property used_in_implementation false [get_files D:/Personal_Project/8B-10B-Encoder-Decoder/Dec8B10B/Dec8B10B.srcs/constrs_1/new/Constraint1.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Dec8B10B -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Dec8B10B.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Dec8B10B_utilization_synth.rpt -pb Dec8B10B_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
